# Generated by Django 4.1.7 on 2023-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phrase_table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyVerb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=50)),
                ("spanish", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pronoun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=50)),
                ("spanish", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="Table",),
    ]
