describe('game start', () => {
  it('passes', () => {
    cy.visit('http://localhost:8080/')
    cy.get('.login > [type="email"]').click().type('cypress@gmail.com')
    cy.get('.login > [type="password"]').click().type('123!@#')
    cy.get('.login > [type="submit"]').click()
    cy.get('[href="/definer"]').click()
    cy.get('.button').click()
    cy.get(':nth-child(1) > :nth-child(2) > div > :nth-child(2)').click()
    cy.get('[href="/tensify"]').click()
    cy.get('.game1 > div > :nth-child(4)').click()
    cy.get('[href="/puzzler"]').click()
    cy.get('.game1 > div > :nth-child(3)').click()
    cy.get('.game1 > div > :nth-child(4)').click()
    cy.get('.game1 > div > :nth-child(5)').click()
    cy.get('.game1 > div > :nth-child(6)').click()
    cy.get('.game1 > div > :nth-child(7)').click()
    cy.get('#buttons').click()
  })
})
